ESite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from graphene_django.views import GraphQLView

import debug_toolbar


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^hitcount/', include('hitcount.urls', namespace='hitcount')),
    # url(r'^weblog/', include('zinnia.urls')),
    # url(r'^comments/', include('django_comments.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^', include('econ.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^__debug__/', include(debug_toolbar.urls)),



# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += url(r'^__debug__/', include(debug_toolbar.urls))

econ/urls.py
from django.conf.urls import url, include

from .views import index,product,autocomplete,setting,slug

app_name = 'econ'
urlpatterns = [
    url(r'^product/$', index.index, name='index'),
    url(r'^product/(?P<product_id>[0-9]+)/$', product.index, name='product'),
    url(r'^cagetory/(?P<cagetory_id>[0-9]+)/$', index.indexbycagetory, name='cagetory'),
    url(r'^brand/(?P<brand_id>[0-9]+)/$', index.indexbybrand, name='brand'),
    url(r'^accounts/$', setting.index, name='settings'),
    url(r'^accounts/profile/$', setting.index, name='settings'),
    # url(r'^settings/$', password.index, name='password'),
    url(r'^autocomplete/', include(autocomplete.urlpatterns), name='auto-complete'),
    url(r'^$', index.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', slug.index, name='slug'),
]

econ/models/Agency.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from .BaseUser import BaseUser
from .Slug import Slug

class Agency(models.Model):
    name = models.CharField(max_length=100,null=True, blank=True)
    logo = models.ImageField(upload_to='media/%Y/%m/%d/%H/%M/%S/',null=True, blank=True)
    member = models.ManyToManyField(
        BaseUser,
        through='AgencyMember',
        through_fields=('agency', 'user'),
    )
    slug = GenericRelation(Slug)
    def __str__(self):
        return self.name

econ/models/AgencyPromotion.py
from django.db import models
from .Promotion import Promotion
from .Agency import Agency
class AgencyPromotion(Promotion):
    apply_to = models.ForeignKey(Agency, on_delete=models.CASCADE)
    

econ/models/BaseUser.py
from django.db import models
from django.contrib.auth.models import User

class BaseUser(User):
    GENDER = (
        ('U','Unknow'), 
        ('M','Male'), 
        ('F','Female'), 
    )
    bio = models.TextField(max_length=500, blank=True)
    address = models.TextField(max_length=500, blank=True)
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER,default='U')
    avatar = models.ImageField(upload_to='media/%Y/%m/%d/%H/%M/%S/',null=True, blank=True)

econ/models/Brand.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from tagging.fields import TagField
from util.abstractmodels import ModifyLog, SlugMixin

class Brand(ModifyLog,SlugMixin,models.Model):
    name = models.CharField(max_length=100)
    sym = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='media/%Y/%m/%d/%H/%M/%S/',null=True, blank=True)
    tags = TagField()

    def __str__(self):
        return self.name

econ/models/Cagetory.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey, TreeManager
from django.contrib.contenttypes.fields import GenericRelation
from tagging.fields import TagField
from util.abstractmodels import ModifyLog, SlugMixin

class Cagetory(MPTTModel, ModifyLog, SlugMixin):
    OPTIONS_CHOICES = (
        (1,'Inherit'),
        (2,'Option by specify'),
        (3,'Option by generic'),
    )

    name = models.CharField(max_length=50)
    parent = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
    )
    allow_choose = models.BooleanField(default=True)
    tags = TagField()

    optiontype = models.IntegerField(choices=OPTIONS_CHOICES, default=1)   

    def option_type(self):
        if self.optiontype == 1 and self.parent_id:
            return self.parent.option_type()
        else :
            return self.optiontype

    def __str__(self):
        return self.name

    def paths(self):
        return self.get_ancestors(ascending=False, include_self=True)

    def path_ids(self):
        return self.paths().values('id')

    def allproducts(self):
        from .Product import Product
        allcagetory_ids = self.get_descendants(include_self=True).values('id')
        return Product.objects.filter(cagetory__id__in=allcagetory_ids)

    # def parent_tags(self):
    #     parents = self.get_ancestors(ascending=False, include_self=False)
    #     tags = Tag.objects.usage_for_queryset(parents)
    #     return tags
    
    def allspecific(self):
        from .Specific import Specific
        path_ids = self.path_ids()
        return Specific.objects.filter(specific_of__id__in=path_ids)

    @staticmethod
    def hash():
        return Cagetory.incrementCount 

    def save(self, *args, **kwargs):
        Cagetory.incrementCount += 1
        print ('incrementCount: %s',Cagetory.incrementCount)
        super(Cagetory, self).save(*args, **kwargs) # Call the "real" save() method.

Cagetory.incrementCount = 0

econ/models/CartItem.py
from django.db import models
from .Product import Product
from .ProductOption import ProductOption
from .Customer import Customer
from django.core.exceptions import ValidationError


class CartItems(models.Model):

    prod = models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=True)
    prod_option = models.ForeignKey(ProductOption,on_delete=models.CASCADE,null=True,blank=True)
    user =  models.ForeignKey(Customer,on_delete=models.CASCADE)
    number = models.IntegerField(default=1)

    def clean(self):
        if (not self.prod_option_id ) == (not self.prod_id):
            raise ValidationError("Either prod or prod_option has value")
        if not self.user_id : 
            raise ValidationError("Empty User")

    def item(self):
        if self.prod_option_id:
            return self.prod_option
        elif self.prod_id:
            return self.prod 
        else:
            return None


    

econ/models/Customer.py
from django.db import models
from django.contrib.auth.models import User

class Customer(User):
    GENDER = (
        ('U','Unknow'), 
        ('M','Male'), 
        ('F','Female'), 
    )
    bio = models.TextField(max_length=500, blank=True)
    address = models.TextField(max_length=500, blank=True)
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER,default='U')
    avatar = models.ImageField(upload_to='media/%Y/%m/%d/%H/%M/%S/',null=True, blank=True)

econ/models/Image.py
from django.db import models


class Image(models.Model):
    class Meta:
         abstract = True
    
    image = models.ImageField(upload_to='media/%Y/%m/%d/%H/%M/%S/',null=True, blank=True)
    link = models.CharField(max_length=300,null=True, blank=True)
    
    def __str__(self):
        return self.url()

    def url(self):
        if(self.image):
            return self.image.url
        else :
            return self.link

econ/models/Product.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from tagging.fields import TagField
from djmoney.models.fields import MoneyField
from ckeditor.fields import RichTextField

# from .Cagetory import Cagetory
from .Brand import Brand
from .Image import Image
from .Promotion import Promotion
from util.abstractmodels import ModifyLog, SlugMixin

class Product(ModifyLog,SlugMixin,models.Model):
    name = models.CharField(max_length=100)
    cagetory = models.ForeignKey('Cagetory')
    branch = models.ForeignKey('Brand')
    tags = TagField()
    spec_types = models.ManyToManyField('Specific')

    # def parent_tags(self):
    #     cagetory = self.cagetory
    #     parents = cagetory.get_ancestors(ascending=False, include_self=True)
    #     tags = Tag.objects.usage_for_queryset(parents)
    #     tags +=  Tag.objects.get_for_object(self.branch)
    #     return tags

    def __str__(self):
        return self.name

    def images(self):
        return [e.url() for e in self.productimage_set.all()]


class ProductImage(Image):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)



class ProductInfo(models.Model):
    product = models.OneToOneField(
        Product,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    info = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.product.name


class ProductPromotion(Promotion) : 
    apply_to = models.ManyToManyField(Product,null=True,blank=True)

econ/views/autocomplete.py
from dal import autocomplete
from django.conf.urls import url
from tagging.models import Tag

from ..models import SpecificDetail,Specific,Cagetory,Product
from django.http import HttpResponse
from django.views.decorators.cache import cache_page




def loginRequired(original_class):
    origin_get_queryset = original_class.get_queryset
    origin_create_object = original_class.create_object

    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return []
        else:
            return origin_get_queryset(self)

    def create_object(self,text):
        if not self.request.user.is_authenticated():
            return []
        else:
            return origin_create_object(self,text)


    original_class.get_queryset = get_queryset 
    original_class.create_object = create_object 

    return original_class



@loginRequired
class SpecificDetailAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = SpecificDetail.objects.all()
        specof = self.forwarded.get('specof', None)
        if specof:
            qs = qs.filter(detail_field__id=specof)
        else :
            return Specific.objects.none()

        if self.q:
            qs = qs.filter(detail_value__istartswith=self.q)

        return qs

    def create_object(self, text):
        specific = self.forwarded.get('specof', None)
        if not specific:
            raise Exception('Choose Specific before create new SpecificDetail')
        return self.get_queryset().create(**{
            self.create_field: text,
            'detail_field_id':specific
        })

@loginRequired
class SpecificAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Specific.objects.all()
        spec_types = self.forwarded.get('spec_types', None)
        
        if spec_types:
            qs = qs.filter(id__in=spec_types)
        if self.q:
            qs = qs.filter(specific_name__istartswith=self.q)


        return qs

    def create_object(self, text):
        specific_of = self.forwarded.get('cagetory', None)
        if not specific_of:
            raise Exception('Choose cagetory before create new Specific')
        return self.get_queryset().create(**{
            self.create_field: text,
            'specific_of_id':specific_of,
        })



@loginRequired
class CagetoryAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Cagetory.objects.all()
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs


@cache_page(60 * 15)
def TagAutocomplete(request):
    return HttpResponse(','.join([e['name'] for e in Tag.objects.all().values('name')]))



app_name = 'econ'
urlpatterns = [
    url(
        r'^specific/$',
        SpecificAutoComplete.as_view(
            create_field='specific_name',
            model=Specific),
        name='spec-ac'
    ),
    url(
        r'^specificdetail/$',
        SpecificDetailAutoComplete.as_view(
            create_field='detail_value',
            model=SpecificDetail),
        name='prodspecdeit-ac'
    ),
    url(
        r'^cagetory/$',
        CagetoryAutoComplete.as_view(),
        name='cagetory-ac'
    ),
    url(
        r'^tags/$',
        TagAutocomplete,
        name='tag-ac'
    ),
]

econ/views/index.py
from django.db.models import Prefetch
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.views import generic
from ..models import Brand,Cagetory,Product,ProductImage,Customer,ProductPromotion,Specific,SpecificDetail

import itertools


# class ProductListView(generic.ListView):
#     template = loader.get_template('list_product.html')
    
# Create your views here.
def index(request):
    product_list = Product.objects.all().prefetch_related(
        'productimage_set',
    )
    template = loader.get_template('list_product.html')
    context = {
        'product_list': product_list,
    }
    return HttpResponse(template.render(context, request))

def indexbycagetory(request,cagetory_id,object=None):
    page = request.GET.get('page') or 1
    cagetoty = object or Cagetory.objects.get(id=cagetory_id)
    product_list = cagetoty.allproducts().prefetch_related(
        'productimage_set',
    )
    template = loader.get_template('list_product.html')
    context = {
        'cagetory_paths' : cagetoty.paths(),
        'product_list': product_list,
    }
    return HttpResponse(template.render(context, request))

def indexbybrand(request,brand_id,object=None):
    page = request.GET.get('page') or 1
    brand = object or Brand.objects.get(id=brand_id)
    product_list = brand.product_set.prefetch_related(
        'productimage_set',
    )
    template = loader.get_template('list_product.html')
    context = {
        'product_list': product_list,
    }
    return HttpResponse(template.render(context, request))

econ/views/product.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.views import generic
from ..models import Brand,Cagetory,Product,ProductImage,Customer,ProductPromotion,Specific,SpecificDetail
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

# class ProductListView(generic.ListView):
#     template = loader.get_template('list_product.html')
    
# Create your views here.
# @login_required
# @cache_page(60 * 15)
def index(request,product_id,object=None):

    product = Product.objects.prefetch_related(
        'productimage_set',
        'productspecdetail_set__spec__detail_field'
    ).select_related(
        'productinfo',
        'branch',
        'cagetory',
    ).get(id=product_id)

    # product_details = product.productspecdetail_set

    template = loader.get_template('product-detail.html')
    context = {
        'product': product,
        # 'product_details': product.productspecdetail_set.all()
    }
    
    return HttpResponse(template.render(context, request))

econ/views/setting.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, redirect
from social_django.models import UserSocialAuth


@login_required
def index(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    try:
        google_login = user.social_auth.get(provider='google-oauth2')
    except UserSocialAuth.DoesNotExist:
        google_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'setting.html', {
        'github_login': github_login,
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'google_login' : google_login,
        'can_disconnect': can_disconnect
    })

econ/views/slug.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.views import generic
from ..models import Cagetory,Product,Brand

from .index import (
    indexbycagetory as cagetoryview,
    indexbybrand as brandview
)
from .product import index as productview
from django.http import Http404


def index(request,slug):
    # try:
    #     slug = TaggedInfo.objects.get(slug=slug)
    #     content_object = slug.content_object
    #     if isinstance(content_object, Cagetory):
    #         return cagetoryview(request,slug.object_id,object=content_object)
    #     elif isinstance(content_object, Product):
    #         return productview(request,slug.object_id,object=content_object)
    #     elif isinstance(content_object, Brand):
    #         return brandview(request,slug.object_id,object=content_object)
    #     else:
    #         raise Http404("No MyModel matches the given query.")
    # except:
    raise Http404("No MyModel matches the given query.")

econ/templates/base.html
{% load static %}
{% load compress %}
<html>
    <head>
<!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "bootstrap.css" %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Optional theme -->
        <link rel="stylesheet" href="{% static "bootstrap-theme.css" %}">
        {% compress css %}
            <link rel="stylesheet" type="text/x-scss" href="{% static "main.scss" %}" />
        {% endcompress %}
        {% comment %}<link rel="stylesheet" href="{% static "main.css" %}">{% endcomment %}

        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static "jquery.js" %}"></script>
        <script src="{% static "bootstrap.js" %}"></script>
        {% comment %} <script src="{% static "main.js" %}"></script> {% endcomment %}
    </head>
    <body>
        {% include "header.html" %}
        {% block content %} {% endblock %}
    </body>
</html>

econ/templates/cagetory_list.html
{% load cache %}
{% comment %} {% cache 3600 cagetory_list cagetory_list_hash %} {% endcomment %}

<div class='menu-root' id='menu-root'>
    
    {% for cagetory in cagetory_list %}
    <div class="cagetory menu-main" id="cagetory-{{cagetory.id}}" data-parentid="cagetory-{{cagetory.parent_id}}">
        <div class="cagetory-title menu-title">
            <a class='product-cagetory' href="{% url 'econ:cagetory' cagetory.id %}">{{cagetory}}</a>
        </div>
        <div class="cagetory-child menu-container">
        </div>
    </div>
    {% endfor %}

    <script>
        !function(){
            var rootElem = document.getElementById('menu-root')
            /** @type {HTMLElement[]}*/
            var childs = [...rootElem.children]
            var childIndex = {}
            for(var e of childs)
                childIndex[e.id] = e;
            
            for(var e of childs) if(childIndex[e.dataset.parentid]){
                /** @type {HTMLElement}*/
                var parent = childIndex[e.dataset.parentid]
                e.remove()
                parent.children[1].appendChild(e);
            }
        }()
    </script>
</div>
{% comment %} {% endcache %} {% endcomment %}

econ/templates/cagetory_path.html
{% if cagetory_paths %}
<h3>
    {% for cagetory in cagetory_paths %}
        <span class='product-cagetory'>
            <a href="{% url 'econ:cagetory' cagetory.id %}">{{cagetory}}</a>
        </span>
    {% endfor %}
</h3>
{% else %}
    <div></div>
{% endif %}

econ/templates/compact_admin_inline.html
{% load i18n admin_urls static %}
<div class="js-inline-admin-formset inline-group"
     id="{{ inline_admin_formset.formset.prefix }}-group"
     data-inline-type="stacked"
     data-inline-formset="{{ inline_admin_formset.inline_formset_data }}">
<fieldset class="module {{ inline_admin_formset.classes }}">
    <h2>{{ inline_admin_formset.opts.verbose_name_plural|capfirst }}</h2>
    {{ inline_admin_formset.formset.management_form }}
    {{ inline_admin_formset.formset.non_form_errors }}

    {% for inline_admin_form in inline_admin_formset %}
        <div class="inline-related{% if inline_admin_form.original or inline_admin_form.show_url %} has_original{% endif %}{% if forloop.last %} empty-form last-related{% endif %}" id="{{ inline_admin_formset.formset.prefix }}-{% if not forloop.last %}{{ forloop.counter0 }}{% else %}empty{% endif %}" >
            <div>
                {% if inline_admin_form.form.non_field_errors %}
                    {{ inline_admin_form.form.non_field_errors }}
                {% endif %}
                {% for fieldset in inline_admin_form %}
                    {% include "admin/includes/fieldset.html" %}
                {% endfor %}
                {% if inline_admin_form.needs_explicit_pk_field %}
                    {{ inline_admin_form.pk_field.field }}
                {% endif %}
                {{ inline_admin_form.fk_field.field }}
            </div>
            {% if inline_admin_formset.formset.can_delete and inline_admin_form.original %}
                <div class="delete" style="padding:0 18px 5px;">
                    {{ inline_admin_form.deletion_field.field }} 
                    {{ inline_admin_form.deletion_field.label_tag }}
                </div>
            {% endif %}
        </div>
    {% endfor %}
</fieldset>
</div>

econ/templates/custom_mptt_filter.html
{% load i18n %}
{% load mptt_admin %}
{% load static %}
{% load compress %}

<h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
{% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static "scss/custom-mptt-filter.scss" %}" />
{% endcompress %}
<script>

    !function(){
        if(!window.mptt_filter_tree){
            window.mptt_filter_tree = true;
            
            addEventListener('load',function(){
                $ = django.jQuery;
                var rawdata =localStorage.getItem('mptt-filter-input')
                try{
                    var data = JSON.parse(rawdata) || {}
                }catch(e){
                    var data = {}
                }

                for(var e of [...$('input[id^=mptt-filter-]')]){
                    e.checked = data[e.id] 
                }
                

                $("input[id^=mptt-filter-]").change(function() {
                    data[this.id] = this.checked
                    localStorage.setItem('mptt-filter-input',JSON.stringify(data))
                });

                var selected = $(".mptt-filter-item > a.selected")[0]

                if(selected){
                    do{
                        var parent = selected.parentElement.parentElement.parentElement
                        selected = parent.children[2];
                        selected && selected.classList.add('boiled');
                        console.log(parent)
                    }while(selected && parent.classList.contains('mptt-filter-item'))
                }
            })

        }
    }()
</script>
<div class='mptt-filter-root'>
    {% for choice in choices %}
        {% include "custom_mptt_filter_tree.html" %}
    {% endfor %}
</div>

econ/templates/custom_mptt_filter_tree.html
{% with local_var=choice.child %}
    {% if local_var %}
        <div class="mptt-filter-item">
            <input type="checkbox" checked id="mptt-filter-{{title}}-{{choice.display.id}}"/>
            {% comment %}id="mptt-filter-{{title}}-{{choice.display.id}}"{% endcomment %}
            <label for="mptt-filter-{{title}}-{{choice.display.id}}"></label>
            <a href="{{ choice.query_string|iriencode }}" {% if choice.selected %} class="selected"{% endif %} >{{choice.display}}</a>
            <div class="mptt-filter-childs">
                {% for choice in local_var %}
                    {% include "custom_mptt_filter_tree.html" %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="mptt-filter-item leaf">
            <a href="{{ choice.query_string|iriencode }}"  {% if choice.selected %} class="selected"{% endif %}  >{{choice.display}}</a>
        </div>
    {% endif %}
{% endwith %}






{% comment %}
{% load i18n %}
{% load mptt_admin %}
<h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul>
{% for choice in choices %}
    <li{% if choice.selected %} class="selected"{% endif %}>
    <a{{ choice.padding_style }} href="{{ choice.query_string|iriencode }}">{{ choice.display }}</a></li>
{% endfor %}
</ul>{% endcomment %}

econ/templates/header.html
<h1>Simple ESite Apps</h1>
<div>
    {% if request.user.is_authenticated %}
        You are loggin at <a href="{% url 'econ:settings' %}">{{ request.user.username }}</a>
        <a href="{% url 'logout' %}">Sign out</a>
    {% else %}
        You aren't loggin, please <a href="{% url 'login' %}">login</a>.
    {% endif %}
</div>
<br/>
<div>
    {% include "cagetory_list.html" %}


    {% comment %} {% if cagetory_list %}
    
        <div class='menu-root'>
            {% for cagetory in cagetory_list %}
                {% include "cagetory_tree.html" %}
            {% endfor %}
        </div>
    {% endif %} {% endcomment %}
</div>

econ/templates/list_product.html
{% extends 'base.html' %}

{% block content %}
    {% include 'cagetory_path.html' %}
    
    <div class="product_list product-grid">
        {% for product in product_list %}
            {% include 'product-item.html' %}
        {% empty %}
            <p>No products are available.</p>
        {% endfor %}
    </div>
{% endblock %}

econ/templates/product-detail.html
{% extends 'base.html' %} {% block content %}
<div class="product-container">
    {% load staticfiles %}
    <script src="{% static 'hitcount/jquery.postcsrf.js' %}"></script>
    {% load hitcount_tags %} {% get_hit_count_js_variables for product as hitcount %}
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            // use the template tags in our JavaScript call
            $.postCSRF("{{ hitcount.ajax_url }}", {
                hitcountPK: "{{ hitcount.pk }}",
                //csrfmiddlewaretoken: getCookie('csrftoken'),
            }).done(function (data) {
                $('<i />').text(data.hit_counted).attr('id', 'hit-counted-value').appendTo('#hit-counted');
                $('#hit-response').text(data.hit_message);
            }).fail(function (data) {
                console.log('POST failed');
                console.log(data);
            });
        });
    </script>
    <h1>{{ product.name }}</h1>
    <h2>{{ product.price }}</h2>

    {% with cagetory_paths=product.cagetory.paths %} {% include 'cagetory_path.html' %} {% endwith %}

    <!-- <div class="product-agency">{{ product.agency }}</div class=""> -->

    {% with details=product.productspecdetail_set.all %}
        <div class="product-details-title">Specification : </div>
        {% include "product_specific_detail.html" %} 
    {% endwith %}
    <div class="product-img">
        {% for image in product.productimage_set.all %}
            <img src="{{image.url}}" alt="" /> 
        {% endfor %}
    </div>

    <div class='product-info'>
        {{ product.productinfo.info|safe }}
    </div>
</div>
{% endblock %}

econ/templates/product-item.html
<div class="product-item"> 
    <a href="{% url 'econ:product' product.id %}">
        <img src="{{product.images|first}}" alt="">      
    </a>
    <div class="product-name" href="{% url 'econ:product' product.id %}">{{ product.name }}</div>
    <div class="product-price">{{ product.price }}</div class="product-price">
    <!-- <div class="product-agency">{{ product.agency }}</div class=""> -->
</div>

econ/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
    {% load staticfiles %}
    <div class="product-container">       
        <h1>{{ product.product_name }}</h1>
        <h2>{{ product.product_price }}</h2>

        {% with cagetory_paths=product.product_cagetory.paths %}
            {% include 'cagetory_path.html' %}
        {% endwith %}
        
        <div class="product-agency">{{ product.product_agency }}</div class="">
        <div class="product-details-title">Specification : </div>
        <div class="product-details">
            {% for detail in product.productspecdetail_set.all %}
                <div class="product-detail">
                    <span class='detail-name'> {{detail.specof}}</span> : 
                    <span class='detail-value'>{{detail.spec}} </span>
                </div>
            {% endfor %}
        </div>
        <div class="product-img">
            {% if product.productimage_set and product.productimage_set.first %}
            {% with product.productimage_set.first as image %}   
                <img src="{{image.image.url}}" alt=""/>
            {% endwith %}
            {% endif %}
        </div>
    </div>
{% endblock %}

econ/templates/product_option_compact.html
<div class="product-option-spec" style="display: flex;">
    {% with details=product.prod_details images=product.prod_images %}
        <div class="product-spec" style="flex:1">
            {% include "product_specific_detail.html" %}
        </div>
        <div class="product-images">
            {% for image in images %}
                <img src="{{image.url}}" style='height: 80px;width: 80px;object-fit: contain;'>
            {% endfor %}
        </div>
    {% endwith %}
</div>

econ/templates/product_specific_detail.html
<table class="product-details">
    <tbody>
        {% for detail in details %}
        <tr class="product-detail">
            <td class='detail-name'> {{detail.spec.detail_field}}</td>
            <td class='detail-value'>{{detail.spec}} </td>
        </tr>
        {% empty %}
        <tr class="product-detail empty">
            <td class='detail-name'> -------------------------- </td>
        </tr>
        {% endfor %}
        <tr class="product-detail product-price">
            <td class='detail-name'>Price</td>
            <td class='detail-value'>{{product.price}} </td>
        </tr>
    </tbody>
</table>